// import './globals.css'
// import Link from "next/link"



// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html>
//       <body>
//         <div className="navbar">
//           <Link href = "/">홈</Link>
//           <Link href = "/list">주차장목록</Link>
          

//         </div>
//         {children}
        
//       </body>
//     </html>
//   )
// }


import './globals.css'
import Link from "next/link"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div>
      <div className="navbar">
        <Link href="/">홈</Link>
        <Link href="/list">주차장목록</Link>
      </div>
      {children}
    </div>
  )
}
